spring.application.name=SpringBoot2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5433/module-3
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create
#debug=true


