spring.application.name=SpringBoot2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5433/module-3
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=create
#debug=true


#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=redis-12610.crce185.ap-seast-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=12610
spring.data.redis.password=aj7zHNjjMWkDdlHzLFjHwk309WrtCcsH
spring.data.redis.ssl.enabled=false