spring.application.name=prod-ready-features
spring.jpa.hibernate.ddl-auto = create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5433/module-3
spring.datasource.username=postgres
spring.datasource.password=123

spring.devtools.restart.enabled =true
spring.devtools.restart.exclude = src/main/java/com/springboot/prod_ready_features/dtos/PostDTO.java

server.port=9000
employeeService.base.url =http://localhost:8080/

logging.level.com.springboot.prod_ready_features.clients.impl=TRACE
logging.pattern.console=%d [%level] %c ---- [%t] %m%n
logging.config=classpath:logback-spring.xml


#actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true


#swagger and open-api
springdoc.api-docs.enabled=true