spring.application.name=docker-learn

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://product-db:5432/product-db
spring.datasource.username=postgres
spring.datasource.password=123
spring.sql.init.mode=always
